### PR TITLE
path changed from fastestforward to jqr

### PR DESCRIPTION
**Pull request by kmayer**

### CODE REVIEW

**Comment by jqr** [comment]
Sorry about the move and the unintended consequences. Thanks for the fix and you should have commit rights again.

**Comment by jqr** [comment]
Merged, but looks like gemnasium and codeclimate need some setup. I'm traveling today so feel free to handle this, otherwise I'll look into it soon.

**Comment by kmayer** [comment]
no worries, brah!

On Wed, Jul 6, 2016 at 2:16 PM, Elijah Miller notifications@github.com
wrote:

> Merged, but looks like gemnasium and codeclimate need some setup. I'm
> traveling today so feel free to handle this, otherwise I'll look into it
> soon.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jqr/heroku_san/pull/175#issuecomment-230909439, or mute
> the thread
> https://github.com/notifications/unsubscribe/AABM5O-IomWwhrYFSoCrFE0Z1F6z4t1rks5qTBshgaJpZM4JGS0n
> .

## 

CTO, PacerPro, Inc. https://www.pacerpro.com
Want to talk to me? Schedule an appointment here:
https://calendly.com/ken-pacerpro/15min

**Comment by jqr** [comment]
Alright, I've got all the badges working again by doing some re-signing up. 💃💃💃

**Pull request merged**
